CREATE TABLE IF NOT EXISTS `#__festival_project` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `asset_id` INT(10) unsigned NOT NULL DEFAULT 0 COMMENT 'FK to the #__assets table.',
  `alias` VARCHAR(100) NOT NULL DEFAULT '',
  `project_title` VARCHAR(100) NOT NULL DEFAULT '',
  `project_title_original_language` VARCHAR(100) NOT NULL DEFAULT '',
  `synopsis` VARCHAR(2048) NOT NULL DEFAULT '',
  `synopsis_original_language` VARCHAR(2048) NOT NULL DEFAULT '',
  `params` text NULL,
  `published` TINYINT(3) NOT NULL DEFAULT 1,
  `created_by` INT(10) unsigned NOT NULL DEFAULT 0,
  `modified_by` INT(10) unsigned NOT NULL DEFAULT 0,
  `created` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
  `modified` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
  `checked_out` int(11) unsigned NOT NULL DEFAULT 0,
  `checked_out_time` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
  `version` INT(10) unsigned NOT NULL DEFAULT 1,
  `hits` INT(10) unsigned NOT NULL DEFAULT 0,
  `access` INT(10) unsigned NOT NULL DEFAULT 0,
  `ordering` INT(11) NOT NULL DEFAULT 0,
  `rules` TEXT NOT NULL DEFAULT '{}',
  PRIMARY KEY (`id`),
  KEY `idx_project_title` (`project_title`),
  KEY `idx_alias` (`alias`),
  KEY `idx_access` (`access`),
  KEY `idx_checkout` (`checked_out`),
  KEY `idx_createdby` (`created_by`),
  KEY `idx_modifiedby` (`modified_by`),
  KEY `idx_state` (`published`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC;
